### ISSUE TITLE
proper tree with your config， can't open

### ISSUE THREAD

**Issue by AndyYuan96** [extric99/Hackintosh-NUC7I7DNKE#3]
Hi, extric99, thanks for your great work. I'm new to Hachintosh, I don't understand your words "SATA Support broken due to Apple dropping the AppleIntelPchSeriesAHCI class in AppleAHCIPort.kext. To workaround this, I added Catalina's patched AppleAHCIPort.kext with the MinKernel set to 20.0.0 as recommended by the OpenCore Install Guide. By default this is disabled to ensure that there are no issues with Catalina. If using the EFI for BigSur enable the kext in the config.plist."
 
what I should enable to use sata in big sur？and i can't open your config with propertree,  proper tell me "ordered dict object has no attribute append".

thanks for your help.

**Comment by AndyYuan96** [comment]
in config.plist, unexpected element at line 444

**Comment by extric99** [comment]
First I am not really sure why ProperTree is throwing these errors. Maybe it is due to some conversion not sure... If you edit with a text editor is it working fine?
Secondly To enable the BigSur workaround you need to go to the kext section and find CtlnaAHCIPort.kext and turn enable to true instead of false. If you have an NVME or run Catalina this is not required.

**Comment by AndyYuan96** [comment]
> First I am not really sure why ProperTree is throwing these errors. Maybe it is due to some conversion not sure... If you edit with a text editor is it working fine?
> Secondly To enable the BigSur workaround you need to go to the kext section and find CtlnaAHCIPort.kext and turn enable to true instead of false. If you have an NVME or run Catalina this is not required.

I figure out, in config.plist,  delete line 443,  <string></string>, then it works.

**Comment by extric99** [comment]
Thanks i will correct it
