### ISSUE TITLE
Broadcom BCM94352Z DW1560  is not working

### ISSUE THREAD

**Issue by NathanDai** [extric99/Hackintosh-NUC7I7DNKE#4]
My Device use 1560 but no Wi-Fi or Bluetooth

**Comment by extric99** [comment]
With this information  I can not help...
Which Nuc are you using?
Did you follow the instructions and apply the correct config.plist. You need to remove the default one because this is for the default wlan card. Use the one with .dw1560 and rename it
Check in hackintool  that the kext that are loaded and provide a screenshot. You should see under extension and the Broadcom kext should be loaded. If they are not loaded it is the wrong config.plist

**Comment by NathanDai** [comment]
My device Is NUC 7i7dnhe and i replace WiFi card to DW1560 and i use  config.plist.dw1560.plist 
Now Bluetooth working fine but WiFi not working
![image](https://user-images.githubusercontent.com/28701315/103454704-7fa39180-4c9b-11eb-82f2-48b79ee6cff8.png)
![image](https://user-images.githubusercontent.com/28701315/103454713-934ef800-4c9b-11eb-985a-b55559e33151.png)
![image](https://user-images.githubusercontent.com/28701315/103454720-a235aa80-4c9b-11eb-8f3f-56e6f294e2ef.png)

**Comment by extric99** [comment]
Please provide a screenshot of Hackintool https://github.com/headkaze/Hackintool as below


![image](https://user-images.githubusercontent.com/33332861/103456301-0c2e6e00-4cf5-11eb-8724-5507ca7ae2d4.png)
The issue is that the en01 interface is not present. Did you delete it? Can you try to add it the network config?
![image](https://user-images.githubusercontent.com/33332861/103456377-ba3a1800-4cf5-11eb-8b3c-4a9a4516db51.png)

**Comment by NathanDai** [comment]
i find the way to fix it ,i disable AirPortBrcm4360, which is now within AirportBRCMfixup.kext.
